
batch_size: 64
sr: 16000
sec: ${dcase}
num_workers: 0

train:
  dataloader:
    batch_size: ${datamodule.batch_size}
    num_workers: ${datamodule.num_workers}
    pin_memory: true
    shuffle: true
  dataset:
    tgt_class: asdkit.datasets.WaveDataset
    audio_channel: first
    path_selector_list:
      - "${data_dir}/formatted/${dcase}/raw/*/train/*.wav"
  batch_sampler: null
  collator:
    tgt_class: asdkit.datasets.DCASEWaveCollator
    sr: ${datamodule.sr}
    sec: ${datamodule.sec}
    shuffle: true
    label_dict_path: ${label_dict_path}
