MACHINE_DICT = {
    "dcase2020-dev": [
        "fan",
        "pump",
        "slider",
        "ToyCar",
        "ToyConveyor",
        "valve",
    ],
    "dcase2020-eval": [
        "fan",
        "pump",
        "slider",
        "ToyCar",
        "ToyConveyor",
        "valve",
    ],
    "dcase2021-dev": [
        "fan",
        "gearbox",
        "pump",
        "slider",
        "ToyCar",
        "ToyTrain",
        "valve",
    ],
    "dcase2021-eval": [
        "fan",
        "gearbox",
        "pump",
        "slider",
        "ToyCar",
        "ToyTrain",
        "valve",
    ],
    "dcase2022-dev": [
        "bearing",
        "fan",
        "gearbox",
        "slider",
        "ToyCar",
        "ToyTrain",
        "valve",
    ],
    "dcase2022-eval": [
        "bearing",
        "fan",
        "gearbox",
        "slider",
        "ToyCar",
        "ToyTrain",
        "valve",
    ],
    "dcase2023-dev": [
        "bearing",
        "fan",
        "gearbox",
        "slider",
        "ToyCar",
        "ToyTrain",
        "valve",
    ],
    "dcase2023-eval": [
        "bandsaw",
        "grinder",
        "shaker",
        "ToyDrone",
        "ToyNscale",
        "ToyTank",
        "Vacuum",
    ],
    "dcase2024-dev": [
        "bearing",
        "fan",
        "gearbox",
        "slider",
        "ToyCar",
        "ToyTrain",
        "valve",
    ],
    "dcase2024-eval": [
        "3DPrinter",
        "AirCompressor",
        "BrushlessMotor",
        "HairDryer",
        "HoveringDrone",
        "RoboticArm",
        "Scanner",
        "ToothBrush",
        "ToyCircuit",
    ],
    "dcase2025-dev": [
        "bearing",
        "fan",
        "gearbox",
        "slider",
        "ToyCar",
        "ToyTrain",
        "valve",
    ],
    "dcase2025-eval": [
        "AutoTrash",
        "BandSealer",
        "CoffeeGrinder",
        "HomeCamera",
        "Polisher",
        "ScrewFeeder",
        "ToyPet",
        "ToyRCCar",
    ],
    "dcase2026-dev": [
        "ToyCar",
        "ToyCarEmu",
        "bearingEmu",
        "fan",
        "gearboxEmu",
        "sliderEmu",
        "valveEmu",
    ],
    "dcase2026-eval": [
        "BlowerDustCollector",
        "Sander",
        "SewingMachine",
        "ToothBrush",
        "ToyDrone",
    ],
}
